[build]
  publish = "out"
  command = "HUGO_BASEURL=$URL gulp build"

[build.environment]
  HUGO_VERSION = "0.49"

[context.production]
  command = "HUGO_BASEURL=$URL gulp build && npm run algolia"

[context.deploy-preview]
  command = "HUGO_BASEURL=$DEPLOY_PRIME_URL gulp build"

[[headers]]
  for = "/*"
  [headers.values]
    Link = [
      "</s/21Cent-Black.woff2>; rel=preload; as=font; type=font/woff2; crossorigin",
      "</s/21Cent-Regular.woff2>; rel=preload; as=font; type=font/woff2; crossorigin",
      "</s/21Cent-Italic.woff2>; rel=preload; as=font; type=font/woff2; crossorigin",
      "</s/21Cent-Bold.woff2>; rel=preload; as=font; type=font/woff2; crossorigin",
      "</s/style.css>; rel=preload; as=style",
      "</j/scripts.js>; rel=preload; as=script"
    ]
