markup = "mmark"

baseURL = "http://kizu.ru/"
sourceRelativeLinksEval = true

DefaultContentLanguage = "en"

title = "kizu.ru"

[permalinks]
posts = "/:slug/"

[Languages]
[Languages.en]
languageCode = "en"
languagePrefix = ""

[Languages.ru]
languageCode = "ru"
languagePrefix = "ru/"
