markup = "mmark"

baseURL = "http://kizu.ru/"
sourceRelativeLinksEval = true

DefaultContentLanguage = "ru"

title = "kizu.ru"

[permalinks]
posts = "/:section/:slug/"

[Languages]
[Languages.en]
languageCode = "en"
languagePrefix = "en/"

[Languages.ru]
languageCode = "ru"
languagePrefix = ""
