markup = "mmark"

baseURL = "https://www.kizu.ru/"
sourceRelativeLinksEval = true

preserveTaxonomyNames = true

DefaultContentLanguage = "en"

title = "kizu.ru"

[author]
name = "Roman Komarov"

[permalinks]
posts = "/:slug/"

[outputs]
home = ["HTML", "JSON", "RSS", "Algolia", 'versions']
page= ["HTML", "JSON"]
section= ["HTML", "JSON"]
taxonomyTerm= ["HTML", "JSON"]
taxonomy= ["HTML", "JSON"]

[outputFormats.versions]
baseName = "versions"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "subtitle", "summary", "content", "date", "publishdate", "permalink"]
params = ["tags"]

[Languages]
[Languages.en]
languageCode = "en"
languagePrefix = ""
diffLanguagePrefix = "ru/"

[Languages.ru]
languageCode = "ru"
languagePrefix = "ru/"
diffLanguagePrefix = ""
